"""add KPI formula type

Revision ID: 2bbae4f826f6
Revises: 307de786fd9d
Create Date: 2026-08-19 16:33:21.548544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2bbae4f826f6"
down_revision: Union[str, Sequence[str], None] = "307de786fd9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpis",
        sa.Column(
            "formula_type",
            sa.String(length=50),
            nullable=False,
            server_default=sa.text("'default'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kpis", "formula_type")
    # ### end Alembic commands ###
