"""add KPI direction

Revision ID: bcd6d78a1d51
Revises: daff9a486505
Create Date: 2026-08-19 12:38:53.012721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcd6d78a1d51"
down_revision: Union[str, Sequence[str], None] = "daff9a486505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        "kpis",
        sa.Column(
            "higher_is_better",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kpis", "higher_is_better")
    # ### end Alembic commands ###
