"""create kpi tables

Revision ID: d7eab8067c53
Revises: aaf2e4b2f9ad
Create Date: 2026-08-18 11:31:48.750193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7eab8067c53'
down_revision: Union[str, Sequence[str], None] = 'aaf2e4b2f9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('warning_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('critical_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpis')
    # ### end Alembic commands ###
