"""add KPI measurement input data

Revision ID: fc897dd1b0f2
Revises: 2bbae4f826f6
Create Date: 2026-08-19 17:27:39.567271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc897dd1b0f2"
down_revision: Union[str, Sequence[str], None] = "2bbae4f826f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kpi_measurements",
        sa.Column(
            "input_data",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kpi_measurements", "input_data")
    # ### end Alembic commands ###
